/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mamet' at '17/07/09 18:04' with Gradle 2.14.1
 *
 * @author mamet, @date 17/07/09 18:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
